export const PRESET_QUOTES = [
  "Core memory unlocked 🔓✨",
  "Living for moments like this 💫",
  "A day to remember forever 🤍",
  "These are the golden days ☀️",
  "Snapshot of pure happiness 📸",
  "Hold onto this feeling ✨",
  "Nothing but good vibes 🌊",
  "Forever grateful for this chapter 📖",
  "Time stood still for a second ⏳",
  "The best days are spent with you 💕",
  "Chasing sunsets and making memories 🌅",
  "Laughing until our stomachs hurt 😂",
  "A beautiful mess 🎨",
  "Proof that magic exists 🪄",
  "My heart is so full ❤️",
  "Just a tiny piece of our epic story 🚀",
  "If I could bottle this feeling up 🍾",
  "Finding joy in the ordinary 🌼",
  "Unplanned moments are the best ones 🎲",
  "Surrounded by my favorite people 🥂",
  "Taking the scenic route 🗺️",
  "Can we rewind to this day? ⏪",
  "Smiles that reached our eyes 😊",
  "Lost in the right direction 🧭",
  "Some places just feel like home 🏡",
  "A pocket full of sunshine ☀️",
  "Creating our own little universe 🌌",
  "Felt cute, never deleting this 💅",
  "The kind of tired you feel after a great day 😴",
  "Just looking at this makes me smile 💖",
  "We clean up pretty nice ✨",
  "Out of office mode: ON 🌴",
  "Sweatpants, messy hair, perfect day 🛋️",
  "Little moments, big memories 🔍",
  "This is what life is all about 🌍",
  "Caught in the act of being happy 🎬",
  "A story I'll tell for years 📜",
  "Better together 🤝",
  "One for the history books 📚",
  "No filter needed for this joy 🚫📸",
  "Dancing through life 💃",
  "Good times & crazy friends 🤪",
  "Living in my own little fairytale 🏰",
  "The highlight reel 🎞️",
  "Just a couple of kids having fun 🎈",
  "Feeling on top of the world 🏔️",
  "The soundtrack to this memory would be amazing 🎵",
  "Collecting moments, not things 🎒",
  "A perfect slice of life 🍕",
  "To be continued... ➡️"
];
